version: '3.1'

services:
  front-end-vue:
    container_name: front-end-vue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'