version: '3.7'

services:
  my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true
    ports:
      - '8081:8080'